[project]
name = "minestatus"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "fastapi (>=0.115.8,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "mcstatus (>=11.1.1,<12.0.0)",
]
